from appV2.contracts.interfaces.REST.controllers.contracts_controller import router
from appV2.contracts.interfaces.REST.controllers.upload_contract_controller import upload_contract
from appV2.contracts.interfaces.REST.controllers.update_contract_controller import update_contract
from appV2.contracts.interfaces.REST.controllers.get_all_contracts_controller import get_all_contracts
from appV2.contracts.interfaces.REST.controllers.get_contract_by_id_controller import get_contract_by_id
from appV2.contracts.interfaces.REST.controllers.get_all_terms_by_contract_id_controller import get_all_terms_by_contract_id

contract_router = router